### PR TITLE
Add diff module.

### PR DESCRIPTION
**Pull request by mirodietiker**
Adding the unofficial diff module sandbox, now with tests.

It was merged to d.o and thus the merge request updated.

(New config lines untested.)

### CODE REVIEW

**Comment by mirodietiker** [comment]
Updated pull request. Diff merged into d.o. including our tests. :-)

**Comment by mirodietiker** [comment]
Paragraphs has no test coverage yet, but we will push this soon a bit.

**Comment by Berdir** [comment]
I already added diff in https://github.com/Berdir/d8modulestatus/pull/11, will merge this when paragraphs has some tests.

**Comment by mirodietiker** [comment]
That's not fair! I was first! ;-)

**Pull request merged**
